public class DaDataInnWrapper{
    public cls_suggestions[] suggestions;
    public class cls_suggestions {
        public String value;	//ООО "СТЕКЛОКОН"
        public String unrestricted_value;	//ООО "СТЕКЛОКОН"
        public cls_data data;
    }
    public class cls_data {
        public String postal_code;	//115114
        public String country;	//Россия
        public String country_iso_code;	//RU
        public String federal_district;	//Центральный
        public String region_fias_id;	//0c5b2444-70a0-4932-980c-b4dc0d3f02b5
        public String region_kladr_id;	//7700000000000
        public String region_iso_code;	//RU-MOW
        public String region_with_type;	//г Москва
        public String region_type;	//г
        public String region_type_full;	//город
        public String region;	//Москва
        public cls_area_fias_id area_fias_id;
        public cls_area_kladr_id area_kladr_id;
        public cls_area_with_type area_with_type;
        public cls_area_type area_type;
        public cls_area_type_full area_type_full;
        public cls_area area;
        public String city_fias_id;	//0c5b2444-70a0-4932-980c-b4dc0d3f02b5
        public String city_kladr_id;	//7700000000000
        public String city_with_type;	//г Москва
        public String city_type;	//г
        public String city_type_full;	//город
        public String city;	//Москва
        public String city_area;	//Южный
        public cls_city_district_fias_id city_district_fias_id;
        public cls_city_district_kladr_id city_district_kladr_id;
        public String city_district_with_type;	//Даниловский р-н
        public String city_district_type;	//р-н
        public String city_district_type_full;	//район
        public String city_district;	//Даниловский
        public cls_settlement_fias_id settlement_fias_id;
        public cls_settlement_kladr_id settlement_kladr_id;
        public cls_settlement_with_type settlement_with_type;
        public cls_settlement_type settlement_type;
        public cls_settlement_type_full settlement_type_full;
        public cls_settlement settlement;
        public String street_fias_id;	//fb4d2fdd-0b4a-4e8d-b8cd-e7a28cfd5798
        public String street_kladr_id;	//77000000000115400
        public String street_with_type;	//Даниловская наб
        public String street_type;	//наб
        public String street_type_full;	//набережная
        public String street;	//Даниловская
        public String house_fias_id;	//cb4d5826-4621-4eca-b60b-5957eaf6c9aa
        public String house_kladr_id;	//7700000000011540004
        public String house_type;	//д
        public String house_type_full;	//дом
        public String house;	//2
        public String block_type;	//к
        public String block_type_full;	//корпус
        public String block;	//4
        public cls_flat_type flat_type;
        public cls_flat_type_full flat_type_full;
        public cls_flat flat;
        public cls_flat_area flat_area;
        public String square_meter_price;	//177863
        public cls_flat_price flat_price;
        public cls_postal_box postal_box;
        public String fias_id;	//cb4d5826-4621-4eca-b60b-5957eaf6c9aa
        public String fias_code;	//77000000000000011540004
        public String fias_level;	//8
        public String fias_actuality_state;	//0
        public String kladr_id;	//7700000000011540004
        public String geoname_id;	//524901
        public String capital_marker;	//0
        public String okato;	//45296559000
        public String oktmo;	//45914000
        public String tax_office;	//7725
        public String tax_office_legal;	//7725
        public String timezone;	//UTC+3
        public String geo_lat;	//55.708112
        public String geo_lon;	//37.6422704
        public String beltway_hit;	//IN_MKAD
        public cls_beltway_distance beltway_distance;
        public cls_metro[] metro;
        public String qc_geo;	//0
        public cls_qc_complete qc_complete;
        public cls_qc_house qc_house;
        public cls_history_values history_values;
        public cls_unparsed_parts unparsed_parts;
        public String source;	//114115, ГОРОД МОСКВА, НАБЕРЕЖНАЯ ДАНИЛОВСКАЯ, 2, 4
        public String qc;	//0
        public cls_phones phones;
        public cls_emails emails;
        public String ogrn_date;	//1035763200000
        public String okved_type;	//2014
        public cls_employee_count employee_count;
        public cls_opf opf;
        public cls_name name;
        public cls_address address;
    }
    public class cls_capital {
    }
    public class cls_management {
        public String name;	//Овсепян Хачатур Меликович
        public String post;	//ДИРЕКТОР
        public cls_disqualified disqualified;
    }
    public class cls_disqualified {
    }
    public class cls_founders {
    }
    public class cls_managers {
    }
    public class cls_source {
    }
    public class cls_qc {
    }
    public class cls_state {
        public String status;	//ACTIVE
        public String actuality_date;	//1586995200000
        public String registration_date;	//728179200000
        public cls_liquidation_date liquidation_date;
    }
    public class cls_liquidation_date {
    }
    public class cls_opf {
        public String type_z;	//2014
        public String code;	//12300
        public String full;	//Общество с ограниченной ответственностью
        public String short_z;	//ООО
    }
    public class cls_name {
        public String full_with_opf;	//ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТЕКЛОКОН"
        public String short_with_opf;	//ООО "СТЕКЛОКОН"
        public cls_latin latin;
        public String full;	//СТЕКЛОКОН
        public String short_z;	//СТЕКЛОКОН
    }
    public class cls_latin {
    }
    public class cls_okveds {
    }
    public class cls_authorities {
    }
    public class cls_documents {
    }
    public class cls_licenses {
    }
    public class cls_finance {
        public cls_tax_system tax_system;
        public cls_income income;
        public cls_expense expense;
        public cls_debt debt;
        public cls_penalty penalty;
    }
    public class cls_tax_system {
    }
    public class cls_income {
    }
    public class cls_expense {
    }
    public class cls_debt {
    }
    public class cls_penalty {
    }
    public class cls_address {
        public String value;	//г Москва, Даниловская наб, д 2 к 4
        public String unrestricted_value;	//115114, г Москва, Даниловский р-н, Даниловская наб, д 2 к 4
        public cls_data data;
    }
    public class cls_area_fias_id {
    }
    public class cls_area_kladr_id {
    }
    public class cls_area_with_type {
    }
    public class cls_area_type {
    }
    public class cls_area_type_full {
    }
    public class cls_area {
    }
    public class cls_city_district_fias_id {
    }
    public class cls_city_district_kladr_id {
    }
    public class cls_settlement_fias_id {
    }
    public class cls_settlement_kladr_id {
    }
    public class cls_settlement_with_type {
    }
    public class cls_settlement_type {
    }
    public class cls_settlement_type_full {
    }
    public class cls_settlement {
    }
    public class cls_flat_type {
    }
    public class cls_flat_type_full {
    }
    public class cls_flat {
    }
    public class cls_flat_area {
    }
    public class cls_flat_price {
    }
    public class cls_postal_box {
    }
    public class cls_beltway_distance {
    }
    public class cls_metro {
        public String name;	//Автозаводская
        public String line;	//Замоскворецкая
        public Double distance;	//0.9
    }
    public class cls_qc_complete {
    }
    public class cls_qc_house {
    }
    public class cls_history_values {
    }
    public class cls_unparsed_parts {
    }
    public class cls_phones {
    }
    public class cls_emails {
    }
    public class cls_employee_count {
    }
    public static DaDataInnWrapper parse(String json){
        return (DaDataInnWrapper) System.JSON.deserialize(json, DaDataInnWrapper.class);
    }
}